const BestSellerProductsList = [
  {
    key: 1,
    title: "Title 1",
    image: "https://cdn.thewirecutter.com/wp-content/media/2022/10/laptopstopicpage-2048px-2029.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: true,
    rating: 2,
  },
  {
    key: 2,
    title: "Title 2",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: false,
    rating: 5,
  },
  {
    key: 3,
    title: "Title 3",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: false,
    rating: 4,
  },
  {
    key: 4,
    title: "Title 4",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: false,
    rating: 3,
  },
  {
    key: 5,
    title: "Title 5",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: false,
    rating: 2.5,
  },
  {
    key: 6,
    title: "Title 6",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "22",
    ifNew: false,
    rating: 4.5,
  },
  {
    key: 7,
    title: "Title 7",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "55",
    originalPrice: "99",
    ifNew: true,
    rating: 4.5,
  },
  {
    key: 8,
    title: "Title 8",
    image: "https://cdn.ttgtmedia.com/rms/onlineimages/hp_elitebook_mobile.jpg",
    lastPrice: "22",
    originalPrice: "99",
    ifNew: true,
    rating: 3.5,
  },
];

  export default BestSellerProductsList